### ISSUE TITLE
Element Mount - one part of the clasp appears to be missing in the model

### ISSUE THREAD

**Issue by danrough** [wahoofitness-legacy/ELEMNT-Mount#1]
Hi - firstly thanks so much for making these models available. I'm hoping to be able to adapt the mount slightly to suit a requirement that I have. I'm looking at the mount though, and one piece of the hinged clasp appears to be missing. I don't suppose that you have that part in another model, which you'd be prepared to share do you?

**Comment by muZZkat** [comment]
Sorry about that, I will see if I can sort it out tomorrow. I need to get the new ELEMNT Bolt versions uploaded as well.

**Comment by danrough** [comment]
Hey @muZZkat, no need to apologise whatsoever! I'm really grateful that you've done this in the first place. Do it when you can!

**Comment by muZZkat** [comment]
I've uploaded some new files and also added the new ELEMNT BOLT models, let me know if there is any issues.

**Comment by PolGuixe** [comment]
Hi @muZZkat is the BOLT mount for the aero handlebars available?  

Here is the product.
https://es-eu.wahoofitness.com/devices/bike-computers/elemnt-bolt-aero-2

I think that this model will be easier to modify that the current Bolt mount. 

Many thanks

**Comment by muZZkat** [comment]
Let me follow up and I should be able to get the latest posted on GitHub.

Murray

**Comment by PolGuixe** [comment]
Great! 👍
